	.text

	/*
         * save the old thread's registers,
         * restore the new thread's registers.
         */

	.globl thread_switch
thread_switch:
	sd ra, 0(a0)          /* save return address */
	sd sp, 8(a0)          /* save stack pointer */
	sd s0, 16(a0)         /* save callee-saved register s0 */
	sd s1, 24(a0)         /* save callee-saved register s1 */
	sd s2, 32(a0)         /* save callee-saved register s2 */
	sd s3, 40(a0)         /* save callee-saved register s3 */
	sd s4, 48(a0)         /* save callee-saved register s4 */
	sd s5, 56(a0)         /* save callee-saved register s5 */
	sd s6, 64(a0)         /* save callee-saved register s6 */
	sd s7, 72(a0)         /* save callee-saved register s7 */
	sd s8, 80(a0)         /* save callee-saved register s8 */
	sd s9, 88(a0)         /* save callee-saved register s9	 */
	sd s10, 96(a0)        /* save callee-saved register s10 */
	sd s11, 104(a0)       /* save callee-saved register s11 */

	ld ra, 0(a1)          /* load new return address */
	ld sp, 8(a1)          /* load new stack pointer */
	ld s0, 16(a1)         /* load new callee-saved register s0 */
	ld s1, 24(a1)         /* load new callee-saved register s1 */
	ld s2, 32(a1)         /* load new callee-saved register s2 */
	ld s3, 40(a1)         /* load new callee-saved register s3 */
	ld s4, 48(a1)         /* load new callee-saved register s4 */
	ld s5, 56(a1)         /* load new callee-saved register s5 */
	ld s6, 64(a1)		 /* load new callee-saved register s6 */
	ld s7, 72(a1)		 /* load new callee-saved register s7 */
	ld s8, 80(a1)		 /* load new callee-saved register s8 */
	ld s9, 88(a1)		 /* load new callee-saved register s9 */
	ld s10, 96(a1)        /* load new callee-saved register s10 */
	ld s11, 104(a1)       /* load new callee-saved register s11 */		 
	
	ret    /* return to ra */
